[package]
name = "kernel"
version = "0.1.0"
authors = ["Akihiro Saiki <akihiro_0605@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
