[tasks.build-bin]
script = "cargo +nightly build --release"

[tasks.build]
dependencies = ["build-bin"]
script = "cp ./target/x86_64-unknown-uefi/release/bootloader-rust.efi ./bootx64.efi"

[tasks.build-debug]
command = "cargo"
args = ["+nightly", "build", "--debug"]

[tasks.clean]
dependencies = ["cargo-cl", "rm-efi"]

[tasks.cargo-cl]
script = "cargo clean"

[tasks.rm-efi]
script = "rm ./bootx64.efi"

[config]
skip_core_tasks = true

[tasks.default]
alias = "build"
